### ISSUE TITLE
Flink Job is not started automatically on deployment of Flink job cluster

### ISSUE THREAD

**Issue by anekdoti** [lyft/flinkk8soperator#129] opened 2019-11-21 15:48 UTC
I tried to deploy the wordcount-operator-example to my Kubernetes cluster. This works so far as all pods are running and I can visit the Web UI of the Flink cluster. 

However, the Flink job in the JAR placed under /opt/flink/flink-web-upload in the Docker image is not started and also not listed under "Submit a new Job". Is this normal behaviour?

I'm using Kubernetes 1.14 and version 0.3.0 of the flinkk8soperator.

Please find the output of `kubectl describe flinkapplication.flink.k8s.io -n flink-operator wordcount-operator-example` attached.
[wordcount-operator-example.txt](https://github.com/lyft/flinkk8soperator/files/3875494/wordcount-operator-example.txt)

The log of the operator contains many lines of the shaped attached below (note that the wordcount-operator-example was successfully deleted as a custom resource before).
[flinkk8soperator.log](https://github.com/lyft/flinkk8soperator/files/3875609/flinkk8soperator.log)

**Comment by anandswaminathan** [comment] 2019-11-21 23:34
@anekdoti Might be related to this - https://github.com/lyft/flinkk8soperator/pull/130

Can you paste the output of the pods ? ` kubectl get pods -n flink-operator`

**Comment by anekdoti** [comment] 2019-11-22 08:52
Hello @anandswaminathan 

thanks for your attention. Here is the output of `kubectl get pods -n flink-operator`:
```
NAME                                                      READY   STATUS    RESTARTS   AGE
flinkoperator-cd9f5ccdb-pd95v                             1/1     Running   0          45h
wordcount-operator-example-f366d27c-jm-bc9545777-6r6hz    1/1     Running   0          16h
wordcount-operator-example-f366d27c-tm-7b99f654bb-s9w29   1/1     Running   0          16h
wordcount-operator-example-f366d27c-tm-7b99f654bb-tddbx   1/1     Running   0          16h
```

**Comment by anekdoti** [comment] 2019-11-22 08:59
Concerning the relation to #130: I also initially had problems with the taskmanagers starting because the taskmanager.network.memory.min was set larger than the JVM heap size. I worked around this by increasing the resource requests for job- and taskmanager to 1000Mi from 200Mi. Maybe I should have mentioned this before.

**Comment by anandswaminathan** [comment] 2019-11-22 20:21
@anekdoti We have found the root cause of the issue. You are running the older version of the operator. We are updating the docs. Sorry for the trouble.

**Comment by anandswaminathan** [comment] 2019-11-22 21:38
@anekdoti 
The quickstart docs have been fixed: https://github.com/lyft/flinkk8soperator/blob/master/docs/quick-start-guide.md

Please start from scratch by deleting the existing resources. We do not want multiple different version again causing issues.

**Comment by anekdoti** [comment] 2019-11-25 15:56
@anandswaminathan 
It works perfectly now! Thank you very much!

**Comment by anandswaminathan** [comment] 2019-11-25 19:23
@anekdoti Great. Closing this.

**Closed by anandswaminathan** 2019-11-25 19:23 UTC
